repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version: check 'uv run ruff --version' to match
    rev: v0.9.0 
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format